#
# +------------------------------------------------------+ #
# |                      PSEmoji                         | #
# +------------------------------------------------------+ #
#
#
#
# Использовать эмодзи на табличках
sign: true
#
# Символ обводки кода эмодзи
surrounding: ':'
#
# Названия страниц менюs
page1: Playstrix Эмодзи [стр. 1]
page2: Playstrix Эмодзи [стр. 2]
page3: Playstrix Премиум Эмодзи ⭐
#
# Размер инвентаря (36/45/54)
invsize: 54
#
# Материал сетки эмодзи
gridmaterial: WHITE_STAINED_GLASS_PANE
#
# Подсказки как использовать эмодзи в меню
hint1: Для того чтобы использовать этот эмодзи в чате
hint2: введите его код или же нажмите на предмет
#
# Сообщение если нету доступа
notpremtext: У вас нету привилегии для доступа к примиум эмодзи!
#
# Сообщение если нету доступа к админ-командам
notadmintext: У вас нету доступа к данной команде!
#
# Коды, символы обычных эмодзи
codesAndEms:
  pog: ᄀ
  pig: ᄁ
  fox: ᄂ
  +1: ᄃ
  -1: ᄄ
  kawaii: ᄅ
  facepalm: ᄆ
  hehe: ᄇ
  nom: ᄈ
  shulker: ᄉ
  psold: ᄊ
  padej: ᄋ
  sadneko: ᄌ
  stitchlove: ᄍ
  woaa: ᄎ
  ban: ᄏ
  bob: ᄐ
  catree: ᄑ
  corn: ᄒ
  drink: ᄓ
  oh: ᄔ
  peepowhy: ᄕ
  peepook: ᄖ
  pepoang: ᄗ
  franciang: ᄘ
  gog: ᄙ
  goosecool: ᄚ
  immaputin: ᄛ
  jari: ᄜ
  jergi: ᄝ
  kekw: ᄞ
  playstrix: ᄟ
  lovem: ᄠ
  maeheart: ᄡ
  mimixlep: ᄢ
  owlcry: ᄣ
  owolove: ᄤ
  peek: ᄥ
  peepolove: ᄦ
  peepoknif: ᄧ
  peepostor: ᄨ
  perfect: ᄩ
  phh: ᄪ
  pingsock: ᄫ
  playmatix: ᄬ
  f: ᄭ
  psmarch: ᄮ
  red: ᄯ
  rozvidka,: ᄰ
  sadcat: ᄱ
  shibashoc: ᄲ
  shyteddy: ᄳ
  slavyanin: ᄴ
  catsmile: ᄵ
  thinkstev: ᄶ
  umaru: ᄷ
  vrunishka: ᄸ
  who: ᄹ
  zhdun: ᄺ
  heart: ᄼ
  fire: ᄽ
  69: ᄾ
  discord: ᄿ
  dyphoy: ᅀ
  rev: ᅁ
  spayron: ᅂ
  spruh: ᅃ
  vovari: ᅄ
#
# Коды, символы премиум эмодзи
codesAndEmsPrem:
  bigpog: ᄻ
  halfheart: ᅅ
  drinking: ᅆ
  popcat: ᅇ
  pepodisco: ᅈ
  rainbowpog: ᅉ
  wha: ᅊ
  pikachu: ᅋ
  rainbow: ᅌ
  shop: ᅍ
  imperatrice: ᅎ
